### ISSUE TITLE
OctaSine causes ableton to crash when loading it

### ISSUE THREAD

**Issue by grainmagic** [greatest-ape/OctaSine#16]
**Describe the bug**
Loading OctaSine in ableton makes it crash

**What did you try to do**
1. Open Ableton 10.1.35
2. Load OctaSine on an empty midi track
3. Ableton crashes

**Expected behavior**
Ableton doesn't crash and you should be able to access the plugin

**Software (please complete the following information):**
 - OctaSine version 0.5.1
 - DAW Ableton Live Intro 10
 - OS: Windows 10

**Additional context**
Processor	Intel(R) Celeron(R) N4000 CPU @ 1.10GHz   1.10 GHz
Installed RAM	4.00 GB (3.77 GB usable)
System type	64-bit operating system, x64-based processor

**Log file contents***
[OctaSine.log](https://github.com/greatest-ape/OctaSine/files/6783126/OctaSine.log)

```
10:36:14 [INFO] init
10:36:14 [INFO] OS: Windows 10.0.19042 (Windows 10 Pro) [64-bit]
10:36:14 [INFO] OctaSine build: v0.5.2 (87b0433)
10:36:14 [ERROR] Couldn't load settings: The system cannot find the path specified. (os error 3)
10:36:15 [INFO] create_descriptor_pool with 64 max sets
10:36:15 [INFO] total 128 views and 64 samplers
10:36:15 [INFO] allocate_one
10:36:15 [INFO] Creating a pipeline layout with 1 sets and 0 root constants
10:36:15 [WARN] Unknown decoration ColMajor
10:36:15 [WARN] Unknown decoration MatrixStride
10:36:15 [WARN] Treating VertexIndex as unsigned
10:36:15 [ERROR] D3DCompile error 8876086c: error X3506: unrecognized compiler target 'vs_5_1'
 
10:36:15 [ERROR] thread 'unnamed' panicked at 'failed to create graphics pipeline: Implementation specific error occurred': C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.7.1\src\device\mod.rs:2251

```

**Comment by greatest-ape** [comment]
@grainmagic Thanks!

Could you please try with the attached OctaSine build and see if it solves the problem? I updated the iced/wgpu dependencies to their respective latest versions.
[octasine.dll.zip](https://github.com/greatest-ape/OctaSine/files/6783818/octasine.dll.zip)

**Comment by grainmagic** [comment]
I tried it out and i'm still getting crashes
[OctaSine.log](https://github.com/greatest-ape/OctaSine/files/6784097/OctaSine.log)
```
13:29:16 [INFO] init
13:29:16 [INFO] OS: Windows 10.0.19042 (Windows 10 Pro) [64-bit]
13:29:16 [INFO] OctaSine build: v0.5.2 (9e98f4c) (dirty)
13:29:16 [ERROR] Couldn't load settings: The system cannot find the path specified. (os error 3)
13:29:16 [INFO] Unable to find extension: VK_EXT_display_surface_counter
13:29:16 [INFO] Unable to find extension: VK_KHR_display
13:29:17 [INFO] Adapter Dx12 AdapterInfo { name: "Intel(R) UHD Graphics 600", vendor: 32902, device: 12677, device_type: DiscreteGpu }
13:29:17 [WARN] The underlying API or device in use does not support enough features to be a fully compliant implementation of WebGPU. A subset of the features can still be used. If you are running this program on native and not in a browser and wish to limit the features you use to the supported subset, call Adapter::downlevel_properties or Device::downlevel_properties to get a listing of the features the current platform supports.
13:29:17 [INFO] Starting on (internal) thread ThreadId(1)
13:29:17 [INFO] Created buffer Valid((0, 1, Dx12)) with BufferDescriptor { label: None, size: 64, usage: COPY_DST | UNIFORM, mapped_at_creation: true }
13:29:17 [INFO] Created texture Valid((0, 1, Dx12)) with TextureDescriptor { label: Some("wgpu_glyph::Cache"), size: Extent3d { width: 2048, height: 2048, depth_or_array_layers: 1 }, mip_level_count: 1, sample_count: 1, dimension: D2, format: R8Unorm, usage: COPY_DST | SAMPLED }
13:29:17 [INFO] Created buffer Valid((1, 1, Dx12)) with BufferDescriptor { label: Some("wgpu_glyph::Cache upload buffer"), size: 25600, usage: COPY_SRC | COPY_DST, mapped_at_creation: false }
13:29:17 [INFO] create_descriptor_pool with 64 max sets
13:29:17 [INFO] total 128 views and 64 samplers
13:29:17 [INFO] allocate_one
13:29:17 [INFO] Created buffer Valid((2, 1, Dx12)) with BufferDescriptor { label: Some("wgpu_glyph::Pipeline instances"), size: 2600000, usage: COPY_DST | VERTEX, mapped_at_creation: false }
13:29:17 [INFO] Creating a pipeline layout with 1 sets and 0 root constants
13:29:17 [WARN] Shader translation error for stage VERTEX: D3DCompile error 8876086c: error X3506: unrecognized compiler target 'vs_5_1'
 
13:29:17 [WARN] Please report it to https://github.com/gfx-rs/naga
13:29:17 [WARN] Try enabling `wgpu/cross` feature as a workaround.
13:29:17 [ERROR] wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    Internal error in VERTEX shader: D3DCompile error 8876086c: error X3506: unrecognized compiler target 'vs_5_1'
 


13:29:17 [ERROR] thread 'unnamed' panicked at 'Handling wgpu errors as fatal by default': C:\Users\j\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.9.0\src\backend\direct.rs:1978
13:29:17 [INFO] Dropping Global

```

**Comment by greatest-ape** [comment]
@grainmagic OK. I'm working on using an OpenGL backend instead of wgpu. Please try out this file:

[OctaSine-Windows-OpenGL.zip](https://github.com/greatest-ape/OctaSine/files/6795131/OctaSine-Windows-OpenGL.zip)

**Comment by grainmagic** [comment]
This one works wonderfully!
Thank you so much!

**Comment by greatest-ape** [comment]
@grainmagic Great! I'll be closing this issue once I create regular OpenGL builds.

Yes, please create a new issue for resizing :-)

**Comment by greatest-ape** [comment]
@grainmagic Could you please try with the latest release? https://github.com/greatest-ape/OctaSine/releases/tag/v0.5.4

**Comment by greatest-ape** [comment]
I'm closing this since the build now defaults to glow (and wgpu dependency was updated if I were to decide to use it again).
