### ISSUE TITLE
0.5.4 crashes when running on Wayland

### ISSUE THREAD

**Issue by napcode** [greatest-ape/OctaSine#33]
**Describe the bug**
0.5.4 crashes when running on Wayland (gnome-shell, ArchLinux) but works when running gnome-shell via X11. 

**What did you try to do**
1. Build debug or release
2. run_gui

**Expected behavior**
GUI shows up.

**Backtrace***
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: CreationFailed', /home/user/.cargo/git/checkouts/iced_baseview-7c672318e3bd7e89/b4d8edb/src/window.rs:232:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1.57.0/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/1.57.0/library/core/src/panicking.rs:100:14
   2: core::result::unwrap_failed
             at /rustc/1.57.0/library/core/src/result.rs:1616:5
   3: iced_baseview::window::IcedWindow<A>::new
   4: baseview::x11::window::Window::window_thread
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /home/user/.cargo/git/checkouts/baseview-9d6c750431f4479e/004065e/src/x11/window.rs:169:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1.57.0/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/1.57.0/library/core/src/panicking.rs:100:14
   2: core::result::unwrap_failed
             at /rustc/1.57.0/library/core/src/result.rs:1616:5
   3: run_gui::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by greatest-ape** [comment]
Thanks.

Wayland currently isn’t supported, because it’s not supported by https://github.com/RustAudio/baseview. I should probably mention this somewhere.

**Comment by greatest-ape** [comment]
I'm closing this until Wayland support is added to baseview.
