### ISSUE TITLE
debian stable SIMD build fails + GUI crashes with ”Next frame: Outdated”

### ISSUE THREAD

**Issue by dromer** [greatest-ape/OctaSine#4]
Installed the nightly cargo toolchain. build went fine until:

```
  [ 81%] Built target sleefavx
  make[2]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  /usr/bin/make -f src/libm/CMakeFiles/sleefgnuabiavx512fsp.dir/build.make src/libm/CMakeFiles/sleefgnuabiavx512fsp.dir/build
  make[2]: Entering directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[2]: Nothing to be done for 'src/libm/CMakeFiles/sleefgnuabiavx512fsp.dir/build'.
  make[2]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[2]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  [ 84%] Built target sleefdetfma4
  /usr/bin/make -f src/libm/CMakeFiles/sleefgnuabiavx512fdp.dir/build.make src/libm/CMakeFiles/sleefgnuabiavx512fdp.dir/build
  make[2]: Entering directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[2]: Nothing to be done for 'src/libm/CMakeFiles/sleefgnuabiavx512fdp.dir/build'.
  make[2]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[2]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  /usr/bin/make -f src/libm/CMakeFiles/sleefavx512f.dir/build.make src/libm/CMakeFiles/sleefavx512f.dir/build
  make[2]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[2]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[2]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  /usr/bin/make -f src/libm/CMakeFiles/dispsse_obj.dir/build.make src/libm/CMakeFiles/dispsse_obj.dir/build
  make[2]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  /usr/bin/make -f src/libm/CMakeFiles/dispavx_obj.dir/build.make src/libm/CMakeFiles/dispavx_obj.dir/build
  /usr/bin/make -f src/libm/CMakeFiles/sleefscalar.dir/build.make src/libm/CMakeFiles/sleefscalar.dir/build
  /usr/bin/make -f src/libm/CMakeFiles/dispscalar_obj.dir/build.make src/libm/CMakeFiles/dispscalar_obj.dir/build
  make[2]: Entering directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[2]: Nothing to be done for 'src/libm/CMakeFiles/sleefavx512f.dir/build'.
  make[2]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[2]: Entering directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[2]: Nothing to be done for 'src/libm/CMakeFiles/dispsse_obj.dir/build'.
  make[2]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[2]: Entering directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[2]: Nothing to be done for 'src/libm/CMakeFiles/dispavx_obj.dir/build'.
  make[2]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[2]: Entering directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[2]: Nothing to be done for 'src/libm/CMakeFiles/sleefscalar.dir/build'.
  make[2]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[2]: Entering directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[2]: Nothing to be done for 'src/libm/CMakeFiles/dispscalar_obj.dir/build'.
  make[2]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  [ 85%] Built target sleefgnuabiavx512fsp
  [ 87%] Built target dispsse_obj
  [ 88%] Built target sleefgnuabiavx512fdp
  /usr/bin/make -f src/libm/CMakeFiles/sleefgnuabi.dir/build.make src/libm/CMakeFiles/sleefgnuabi.dir/depend
  make[2]: Entering directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  cd /home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef /home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/src/libm /home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build /home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build/src/libm /home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build/src/libm/CMakeFiles/sleefgnuabi.dir/DependInfo.cmake --color=
  [ 91%] Built target sleefavx512f
  [ 92%] Built target dispavx_obj
  [ 95%] Built target dispscalar_obj
  [ 96%] Built target sleefscalar
  /usr/bin/make -f src/libm/CMakeFiles/sleef.dir/build.make src/libm/CMakeFiles/sleef.dir/depend
  make[2]: Entering directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  cd /home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef /home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/src/libm /home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build /home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build/src/libm /home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build/src/libm/CMakeFiles/sleef.dir/DependInfo.cmake --color=
  make[2]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  /usr/bin/make -f src/libm/CMakeFiles/sleefgnuabi.dir/build.make src/libm/CMakeFiles/sleefgnuabi.dir/build
  make[2]: Entering directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[2]: Nothing to be done for 'src/libm/CMakeFiles/sleefgnuabi.dir/build'.
  make[2]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[2]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  /usr/bin/make -f src/libm/CMakeFiles/sleef.dir/build.make src/libm/CMakeFiles/sleef.dir/build
  make[2]: Entering directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[2]: Nothing to be done for 'src/libm/CMakeFiles/sleef.dir/build'.
  make[2]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  [ 98%] Built target sleefgnuabi
  [100%] Built target sleef
  make[1]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  /usr/bin/cmake -E cmake_progress_start /home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build/CMakeFiles 0
  /usr/bin/make -f CMakeFiles/Makefile2 preinstall
  make[1]: Entering directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  make[1]: Nothing to be done for 'preinstall'.
  make[1]: Leaving directory '/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/build'
  Install the project...
  /usr/bin/cmake -P cmake_install.cmake
  -- Install configuration: "RelWithDebInfo"
  -- Up-to-date: /home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/lib/libsleef.a
  -- Up-to-date: /home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/include/sleef.h
  -- Up-to-date: /home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/lib/pkgconfig/sleef.pc
  -- Up-to-date: /home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/lib/libsleefgnuabi.a
  cargo:root=/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out
  cargo:rustc-link-lib=static=sleef
  cargo:rustc-link-search=native=/home/dreamer/Sources/_audio/_plugins/OctaSine/target/release/build/sleef-sys-59a35f00c99994cf/out/lib

  --- stderr
     Entering             /home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/src
     Called from: [1]	/home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/CMakeLists.txt
     Entering             /home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/src/libm
     Called from: [1]	/home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/src/CMakeLists.txt
     Returning to         /home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/src
     Called from: [1]	/home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/src/CMakeLists.txt
     Entering             /home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/src/common
     Called from: [1]	/home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/src/CMakeLists.txt
     Returning to         /home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/src
     Called from: [1]	/home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/src/CMakeLists.txt
     Returning to         /home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef
     Called from: [1]	/home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/CMakeLists.txt
     Target system: Linux-5.10.0-0.bpo.5-amd64
     Called from: [1]	/home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/CMakeLists.txt
     Target processor: x86_64
     Called from: [1]	/home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/CMakeLists.txt
     Host system: Linux-5.10.0-0.bpo.5-amd64
     Called from: [1]	/home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/CMakeLists.txt
     Host processor: x86_64
     Called from: [1]	/home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/CMakeLists.txt
     Detected C compiler: GNU @ /usr/bin/cc
     Called from: [1]	/home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/CMakeLists.txt
     CMake: 3.16.3
     Called from: [1]	/home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/CMakeLists.txt
     Make program: /usr/bin/make
     Called from: [1]	/home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/CMakeLists.txt

     Called from: [1]	/home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/CMakeLists.txt
  *** Note: Parallel build is only supported with Ninja ***
     Called from: [1]	/home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/CMakeLists.txt

     Called from: [1]	/home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/sleef/CMakeLists.txt
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:425:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:435:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:444:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:453:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:463:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:472:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:481:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:491:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:500:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:509:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:519:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:528:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:790:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:800:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:809:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:818:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:828:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:837:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:846:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:425:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:435:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:444:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:453:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:463:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:472:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:481:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:491:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:500:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:509:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:519:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:528:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:790:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:800:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:809:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:818:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:828:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:837:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  /usr/lib/llvm-7/lib/clang/7.0.1/include/avx512bwintrin.h:846:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
  fatal error: too many errors emitted, stopping now [-ferror-limit=], err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', /home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/build.rs:142:10
  stack backtrace:
     0:     0x560b373ac170 - std::backtrace_rs::backtrace::libunwind::trace::hfa838fc631229987
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
     1:     0x560b373ac170 - std::backtrace_rs::backtrace::trace_unsynchronized::h93a23e36ec026219
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x560b373ac170 - std::sys_common::backtrace::_print_fmt::hba56c7f796a4152f
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x560b373ac170 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h214637f1e26310e1
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/sys_common/backtrace.rs:46:22
     4:     0x560b373d220c - core::fmt::write::h7aa6cd0067dca82a
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/core/src/fmt/mod.rs:1110:17
     5:     0x560b373a8b55 - std::io::Write::write_fmt::heb07fc0616bbd06d
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/io/mod.rs:1588:15
     6:     0x560b373aeb2b - std::sys_common::backtrace::_print::h2c2441c37e894fb5
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/sys_common/backtrace.rs:49:5
     7:     0x560b373aeb2b - std::sys_common::backtrace::print::h4fb679ac439362ea
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/sys_common/backtrace.rs:36:9
     8:     0x560b373aeb2b - std::panicking::default_hook::{{closure}}::h56bbadec2356e5d2
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/panicking.rs:208:50
     9:     0x560b373ae601 - std::panicking::default_hook::hb25822b45f6fdc4e
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/panicking.rs:225:9
    10:     0x560b373af1f4 - std::panicking::rust_panic_with_hook::h4da5578e7277d2d4
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/panicking.rs:622:17
    11:     0x560b373aecd7 - std::panicking::begin_panic_handler::{{closure}}::h003783ddb3cba4e8
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/panicking.rs:519:13
    12:     0x560b373ac64c - std::sys_common::backtrace::__rust_end_short_backtrace::hd138d2032731ed21
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/sys_common/backtrace.rs:141:18
    13:     0x560b373aec39 - rust_begin_unwind
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/panicking.rs:515:5
    14:     0x560b36df9a61 - core::panicking::panic_fmt::hbe99dddd3092ba3c
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/core/src/panicking.rs:92:14
    15:     0x560b36df9b53 - core::result::unwrap_failed::hf79563fef9d11ab8
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/core/src/result.rs:1355:5
    16:     0x560b36e03446 - core::result::Result<T,E>::expect::h06712fec5b6af28f
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/core/src/result.rs:997:23
    17:     0x560b36dff087 - build_script_build::main::hd17350fdb5912970
                                 at /home/dreamer/.cargo/git/checkouts/sleef-sys-19b817f705a3e80d/f0a65b8/build.rs:138:20
    18:     0x560b36dffa2b - core::ops::function::FnOnce::call_once::h98d8bbb42ee8a553
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/core/src/ops/function.rs:227:5
    19:     0x560b36e03e5e - std::sys_common::backtrace::__rust_begin_short_backtrace::h79cb0a0ad5b43d4f
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/sys_common/backtrace.rs:125:18
    20:     0x560b36e01241 - std::rt::lang_start::{{closure}}::h2bd24ce52f66acb1
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/rt.rs:49:18
    21:     0x560b373af7f9 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd933294140eb11aa
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/core/src/ops/function.rs:259:13
    22:     0x560b373af7f9 - std::panicking::try::do_call::h8342fe3d9218b807
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/panicking.rs:401:40
    23:     0x560b373af7f9 - std::panicking::try::hcbd73d6d0d58a8f0
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/panicking.rs:365:19
    24:     0x560b373af7f9 - std::panic::catch_unwind::hde9cf73f810acfcc
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/panic.rs:434:14
    25:     0x560b373af7f9 - std::rt::lang_start_internal::heb39e7ea6e5d6f6f
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/rt.rs:34:21
    26:     0x560b36e01220 - std::rt::lang_start::h8f523ee877542271
                                 at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/rt.rs:48:5
    27:     0x560b36dff3fc - main
    28:     0x7f9d7e4a809b - __libc_start_main
    29:     0x560b36dfa25a - _start
    30:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by greatest-ape** [comment]
@dromer Thanks for opening this issue. I'm looking into it.

If you want to get the plugin working in the meantime, please try compiling it without sleef SIMD acceleration:

`cargo build --release -p octasine_vst2_plugin`

**Comment by dromer** [comment]
Cool, that seems to build.

Where is the resulting VST2 though, is it `135M Jun 13 15:18 liboctasine.so`?
This seems awfully big.

Carla is able to load the DSP, however the UI segfaults when I try to open it.

**Comment by greatest-ape** [comment]
Great.

Yes, that should be the correct file. I'll look into the huge file size. The reason might be the inclusion of debug symbols, but I don't know for sure.

Could you please paste the contents of "$HOME/tmp/OctaSine.log" after trying to open the UI?

**Comment by greatest-ape** [comment]
Does running `git pull` and compiling again make `liboctasine.so` smaller? I turned off generation of debug symbols. The file is about 16 MB when built on Ubuntu by the CI system after that change.

Also, does running `git checkout update-sleef` and recompiling with simd support fix the original compilation failure?

**Comment by dromer** [comment]
- Logfile: https://mrtoasted.com/~dreamer/logs/OctaSine.log

- Now it's `9.6M Jun 13 21:45 liboctasine.so` which indeed seems more reasonable :) (still segfaulting)

- `sleef-sys` still fails to build in this branch

**Comment by greatest-ape** [comment]
Thanks.

It seems like the UI segfault is the error described here: https://github.com/hecrj/iced/pull/667 . The OctaSine UI unfortunately isn’t very battle tested and errors like these tend to pop up.

OK, thanks for trying. I’ll have to look into that further.

**Comment by greatest-ape** [comment]
Pasting most relevant part of your log for future reference:

```
16:50:02 [ERROR] thread 'unnamed' panicked at 'Next frame: Outdated': /home/dreamer/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_wgpu-0.4.0/src/window/compositor.rs:126
```

**Comment by greatest-ape** [comment]
I pushed another commit to `update-sleef` to disable AVX-512 in sleef. Building on Debian 10 works on my computer even without this fix, but my processor isn't AVX-512-compatible, so I figure that could be the reason why it fails for you. Anyway, if you could try out building once more, that would be great.

**Comment by greatest-ape** [comment]
@dromer Could you please try building from this branch? It might fix the GUI issue: https://github.com/greatest-ape/OctaSine/tree/glow

**Comment by dromer** [comment]
Sorry I'll try looking at this again some time. etoomanyprojects :)

**Comment by greatest-ape** [comment]
No problem :-)
